<?php

namespace Sesser\Scurl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-02 at 21:02:22.
 * @ignore
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Request
	 */
	protected $request;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->request = new Request('http://httptest.instaphp.com/test/get', [
			'options' => ['user-agent' => 'RequestTest/1.0']
		]);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
	
	/**
	 * @covers Scurl\Request::initialize
	 */
	public function testInitialize()
	{
		$this->assertInstanceOf('\Sesser\Scurl\Request', $this->request);
		$this->assertEquals('http://httptest.instaphp.com/test/get', $this->request->url);
		$req = new Request($this->request->url, [
			'headers' => [ 'X-Powered-By' => 'Scurl/PHP' . PHP_VERSION],
			'options' => ['user-agent' => 'Scurl/1.0'],
			'auth' => [ 'user' => 'foo', 'pass' => 'passwd']
		]);
		$this->assertEquals($this->request->url, $req->url);
		$this->assertEquals('Scurl/1.0', $req->options['user-agent']);
		
	}
	
	/**
	 * @covers Scurl\Request::__construct
	 */
	public function testInstance()
	{
		$this->assertInstanceOf('\Sesser\Scurl\Request', $this->request);
		$this->assertEquals('RequestTest/1.0', $this->request->options['user-agent']);
		
	}
}
