<?php

namespace Scurl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-02 at 21:02:22.
 */
class ScurlTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Scurl
	 */
	protected $scurl;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->scurl = new Scurl();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
	
	/**
	 * @covers Scurl\Request::__construct
	 * @covers Scurl\Request::initialize
	 */
	public function testInstanceAndInit()
	{
		$this->assertInstanceOf('\Scurl\Scurl', $this->scurl);
	}

	/**
	 * @covers Scurl\Scurl::get
	 * @covers Scurl\Scurl::request
	 * @covers Scurl\Request::send
	 */
	public function testGet()
	{
		$res = $this->scurl->get('http://httptest.instaphp.com/test/get', '_method='.__FUNCTION__.'&test=get');
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertNotEmpty($res->body);
		$json = json_decode($res->body, TRUE);
		$this->assertEquals(__FUNCTION__, $json['request_get_parameters']['_method']);
		$this->assertEquals(Request::METHOD_GET, $json['request_method']);
		
		$res = $this->scurl->get('http://httptest.instaphp.com/test/get', ['_method' => __FUNCTION__, 'test' => 'get']);
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertNotEmpty($res->body);
		$json = json_decode($res->body, TRUE);
		$this->assertEquals(__FUNCTION__, $json['request_get_parameters']['_method']);
		$this->assertEquals(Request::METHOD_GET, $json['request_method']);
	}

	/**
	 * @covers Scurl\Scurl::post
	 * @covers Scurl\Scurl::request
	 * @covers Scurl\Request::send
	 */
	public function testPost()
	{
		$res = $this->scurl->post('http://httptest.instaphp.com/test/post', '_method='.__FUNCTION__.'&test=post');
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertNotEmpty($res->body);
		$json = json_decode($res->body, TRUE);
		$this->assertEquals(__FUNCTION__, $json['request_post_parameters']['_method']);
		$this->assertEquals(Request::METHOD_POST, $json['request_method']);
		$res = $this->scurl->post('http://httptest.instaphp.com/test/post', ['_method' => __FUNCTION__, 'test' => 'post']);
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertNotEmpty($res->body);
		$json = json_decode($res->body, TRUE);
		$this->assertEquals(__FUNCTION__, $json['request_post_parameters']['_method']);
		$this->assertEquals(Request::METHOD_POST, $json['request_method']);
		
	}

	/**
	 * @covers Scurl\Scurl::put
	 * @covers Scurl\Scurl::request
	 * @covers Scurl\Request::send
	 */
	public function testPut()
	{
		
		$res = $this->scurl->put('http://httptest.instaphp.com/test/put/' . basename(TEST_PUTFILE), '', ['data' => TEST_PUTFILE]);
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertNotEmpty($res->body);
		$res = $this->scurl->put('http://httptest.instaphp.com/test/put', ['_method' => __FUNCTION__], ['data' => '_method=' . __FUNCTION__ . '&test=put']);
		$json = json_decode($res->body, TRUE);
		$this->assertEquals(__FUNCTION__, $json['request_put_parameters']['_method']);
		$this->assertEquals(Request::METHOD_PUT, $json['request_method']);
		
	}

	/**
	 * @covers Scurl\Scurl::delete
	 * @covers Scurl\Scurl::request
	 * @covers Scurl\Request::send
	 */
	public function testDelete()
	{
		$res = $this->scurl->delete('http://httptest.instaphp.com/test/delete/' . basename(TEST_PUTFILE), ['_method' => __FUNCTION__, 'test' => 'delete']);
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertNotEmpty($res->body);
		$json = json_decode($res->body, TRUE);
		$this->assertEquals(__FUNCTION__, $json['request_get_parameters']['_method']);
		$this->assertEquals(Request::METHOD_DELETE, $json['request_method']);
		
	}

	/**
	 * @covers Scurl\Scurl::head
	 * @covers Scurl\Scurl::request
	 * @covers Scurl\Request::send
	 */
	public function testHead()
	{
		$res = $this->scurl->head('http://httptest.instaphp.com/test/head', ['_method' => __FUNCTION__, 'test' => 'head']);
		$this->assertInstanceOf('\Scurl\Response', $res);
		$this->assertEmpty($res->body);
		$this->assertNotEmpty($res->headers);
		$this->assertEquals(__FUNCTION__, $res->headers['HTTPTEST__method']);
		$this->assertEquals(Request::METHOD_HEAD, $res->headers['HTTPTEST_METHOD']);
	}

	/**
	 * @covers Scurl\Scurl::request
	 */
	public function testRequest()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
